"""Applies the platform settings WealthBuddy needs to the folders generated by `flutter create`.
Safe to run more than once: every edit checks whether it's already there."""
import pathlib, plistlib, re, shutil, sys

root = pathlib.Path(__file__).resolve().parent.parent
android = root / "android" / "app"


def edit(path, fn):
    p = pathlib.Path(path)
    if not p.exists():
        print(f"skip (missing): {p}")
        return
    before = p.read_text()
    after = fn(before)
    if after != before:
        p.write_text(after)
        print(f"patched: {p.relative_to(root)}")


# --- Android: Gradle -------------------------------------------------------
def gradle(s):
    # minSdk 24: needed by the secure storage and biometric plugins
    s = re.sub(r"minSdk\s*=\s*flutter\.minSdkVersion", "minSdk = 24", s)
    s = re.sub(r"minSdkVersion\s+flutter\.minSdkVersion", "minSdkVersion 24", s)
    # Core library desugaring: required by flutter_local_notifications for scheduled notifications
    if "isCoreLibraryDesugaringEnabled" not in s and "coreLibraryDesugaringEnabled" not in s:
        s = s.replace("compileOptions {", "compileOptions {\n        isCoreLibraryDesugaringEnabled = true", 1)
    if "desugar_jdk_libs" not in s:
        s = s.rstrip() + '\n\ndependencies {\n    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")\n}\n'
    return s

edit(android / "build.gradle.kts", gradle)

# --- Android: manifest -----------------------------------------------------
PERMS = ["android.permission.POST_NOTIFICATIONS", "android.permission.RECEIVE_BOOT_COMPLETED", "android.permission.USE_BIOMETRIC"]
RECEIVERS = '''        <receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />
        <receiver android:exported="false" android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED"/>
                <action android:name="android.intent.action.QUICKBOOT_POWERON" />
                <action android:name="com.htc.intent.action.QUICKBOOT_POWERON"/>
            </intent-filter>
        </receiver>
'''

def manifest(s):
    for perm in PERMS:
        if perm not in s:
            s = s.replace("<application", f'<uses-permission android:name="{perm}"/>\n    <application', 1)
    # No cloud backup: the encryption key can't be restored with it, and the data stays on this phone.
    if "android:allowBackup" not in s:
        s = s.replace("<application", '<application android:allowBackup="false" android:fullBackupContent="false"', 1)
    if "ScheduledNotificationReceiver" not in s:
        s = s.replace("</application>", RECEIVERS + "    </application>", 1)
    # App lock: local_auth needs a FragmentActivity (when the manifest names the Flutter activity directly)
    s = s.replace('"io.flutter.embedding.android.FlutterActivity"', '"io.flutter.embedding.android.FlutterFragmentActivity"')
    return s

edit(android / "src" / "main" / "AndroidManifest.xml", manifest)

# --- Android: MainActivity ---------------------------------------------------
# FlutterFragmentActivity (needed by local_auth), plus the "wealthbuddy/files" channel that saves and opens
# backup files through Android's own file dialogs, so nothing leaves the phone unless the user moves it.
MAIN_ACTIVITY = """package {pkg}

import android.app.Activity
import android.content.Intent
import io.flutter.embedding.android.FlutterFragmentActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel

class MainActivity : FlutterFragmentActivity() {{
    private var pending: MethodChannel.Result? = null
    private var toSave: ByteArray? = null

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {{
        super.configureFlutterEngine(flutterEngine)
        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, "wealthbuddy/files").setMethodCallHandler {{ call, result ->
            if (pending != null) {{
                result.error("busy", "A file dialog is already open", null)
                return@setMethodCallHandler
            }}
            when (call.method) {{
                "save" -> {{
                    toSave = call.argument<ByteArray>("bytes")
                    pending = result
                    val intent = Intent(Intent.ACTION_CREATE_DOCUMENT)
                        .addCategory(Intent.CATEGORY_OPENABLE)
                        .setType("application/octet-stream")
                        .putExtra(Intent.EXTRA_TITLE, call.argument<String>("name"))
                    startActivityForResult(intent, SAVE)
                }}
                "open" -> {{
                    pending = result
                    val intent = Intent(Intent.ACTION_OPEN_DOCUMENT)
                        .addCategory(Intent.CATEGORY_OPENABLE)
                        .setType("*/*")
                    startActivityForResult(intent, OPEN)
                }}
                else -> result.notImplemented()
            }}
        }}
    }}

    @Deprecated("Deprecated in Java")
    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {{
        super.onActivityResult(requestCode, resultCode, data)
        if (requestCode != SAVE && requestCode != OPEN) return
        val result = pending ?: return
        pending = null
        val uri = data?.data
        if (resultCode != Activity.RESULT_OK || uri == null) {{
            toSave = null
            result.success(null)
            return
        }}
        try {{
            if (requestCode == SAVE) {{
                contentResolver.openOutputStream(uri, "wt")?.use {{ it.write(toSave ?: ByteArray(0)) }}
                toSave = null
                result.success(true)
            }} else {{
                val bytes = contentResolver.openInputStream(uri)?.use {{ it.readBytes() }}
                result.success(bytes)
            }}
        }} catch (e: Exception) {{
            result.error("io", e.message, null)
        }}
    }}

    companion object {{
        private const val SAVE = 4711
        private const val OPEN = 4712
    }}
}}
"""

for main in (android / "src" / "main").rglob("MainActivity.*"):
    pkg = re.search(r"^package\s+([\w.]+)", main.read_text(), re.M).group(1)
    kt = main.with_suffix(".kt")
    if main.suffix != ".kt":
        main.unlink()
    kt.write_text(MAIN_ACTIVITY.format(pkg=pkg))
    print("written:", kt)

# --- Android: notification icon, kept through resource shrinking -----------
res = android / "src" / "main" / "res"
if res.exists():
    (res / "drawable").mkdir(exist_ok=True)
    shutil.copy(root / "assets" / "brand" / "ic_stat_wb.png", res / "drawable" / "ic_stat_wb.png")
    (res / "raw").mkdir(exist_ok=True)
    (res / "raw" / "keep.xml").write_text('<?xml version="1.0" encoding="utf-8"?>\n'
                                          '<resources xmlns:tools="http://schemas.android.com/tools" tools:keep="@drawable/ic_stat_wb" />\n')
    print("copied: notification icon")

# --- iOS: Face ID prompt text ----------------------------------------------
plist = root / "ios" / "Runner" / "Info.plist"
if plist.exists():
    with open(plist, "rb") as f:
        data = plistlib.load(f)
    if "NSFaceIDUsageDescription" not in data:
        data["NSFaceIDUsageDescription"] = "Unlock WealthBuddy with Face ID."
        with open(plist, "wb") as f:
            plistlib.dump(data, f)
        print("patched: ios/Runner/Info.plist")

print("platform patches done")
